name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DamianReeves/write-file-action
        with:
          path: Dockerfile
          contents: |
            echo "FROM node:10-slim
            WORKDIR /app
            RUN npm install
            RUN npm run build
            EXPOSE 8080:80
            CMD ['npm', 'start']"
          write-mode: overwrite
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: docker push
        run: |
          docker push acsysio/acsys
