name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Create Dockerfile
        run: echo -e "FROM node:alpine\nWORKDIR /app\nCOPY ./ /app\nRUN npm install --force\nRUN npm run build-linux\nEXPOSE 8080\nCMD [\"npm\", \"start\"]" >> Dockerfile
      - name: View file
        run: cat Dockerfile
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: docker push
        run: |
          docker push acsysio/acsys
