name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: View file
        run: cat Dockerfile
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cbridges1/acsys
      - name: docker push
        run: |
          docker push cbridges1/acsys